version: "3"
services:
  database:
    image: "mongo"
    container_name: "expense_tracker_db"
    environment:
      - MONGO_INITDB_DATABASE=expenses_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata:
    driver: "local"
